
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    restart: always

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL: "PLAINTEXT"
      KAFKA_LISTENER_PORT: 9092
      KAFKA_LISTENER_NAME: "PLAINTEXT"
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      retries: 3
    networks:
      - kafka-net
    restart: always

  app:
    build: .
    container_name: guide_us
    ports:
      - "8080:8080"  # 애플리케이션 포트 매핑
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      REDIS_HOST: "redis"
    depends_on:
      - kafka
      - redis
    networks:
      - kafka-net
    restart: always


networks:
  kafka-net:
    driver: bridge
